select * from customer limit 20;

-- What is the total revenue generated by male vs. female customers?

select gender,SUM(purchase_amount ) as revenue
from customer
group by gender;


-- 🔹 Which customers used a discount but still spent more than the average purchase amount?

select customer_id,purchase_amount
from customer
where discount_applied='Yes' and purchase_amount >= (select AVG(purchase_amount) from customer) ;


-- 🔹 Which are the top 5 products with the highest average review rating?

select item_purchased,avg(review_rating) as "Average Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;
-- 🔹 Compare the average purchase amounts between Standard and Express shipping.


select shipping_type,
round(avg(purchase_amount),2) as avg_purchase
from customer
where shipping_type in ('standard','express')
group by shipping_type;


-- 🔹 Do subscribed customers spend more?
-- Compare both:
-- Average spend
-- Total revenue between subscribe and non-subscribe.  l
-- between subscribed and non-subscribed customers.


select subscription_status ,
count(customer_id) as total_customer,
round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue ,avg_spend desc;


-- 🔹 Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
round(100 * sum(case when discount_applied='Yes' then 1 else 0 end)/count(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

-- 🔹 Segment customers into:
-- New
-- Returning
-- Loyal
-- based on their total number of previous purchases, and show the count of each segment.


with customer_type as(
select customer_id ,previous_purchases,
case 
	when previous_purchases= 1 then 'new'
	when previous_purchases between 2 and 10 then 'returning'
	else 'loyal'
	end as customer_segment
from customer	
)
select customer_segment,count(*) as "number of customer"
from customer_type
group by customer_segment;

-- 🔹 What are the top 3 most purchased products within each category?


WITH item_counts AS (
    SELECT category, item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (
               PARTITION BY category 
               ORDER BY COUNT(customer_id) desc
           ) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)

SELECT item_rank, category, item_purchased, total_orders
FROM item_counts 
WHERE item_rank <= 3;

-- 🔹 Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases >5
group by subscription_status;

-- 🔹  What is the revenue contribution of each age group?

select age_group,
sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;